"""filing_chunks: chunk text, metadata and embeddings

Revision ID: 0002_filing_chunks
Revises: 0001_initial
Create Date: 2026-09-04

Vectors live in the application database, not a separate service. At this corpus
size a second datastore would be pure operational cost, and co-locating them
means a metadata filter is a WHERE clause the planner applies *before* the
top-k, instead of a post-filter over an approximate result set.

Written as raw DDL rather than `op.create_table` because the embedding column
has no SQLAlchemy type without the `pgvector` package, and because its type is
decided at migration time -- see below. For the same reason `filing_chunks` is
deliberately absent from `db/models.py`: a table whose column type depends on
the target server cannot be represented in `Base.metadata`, and pretending
otherwise would make `scripts/check_migration.py` report drift forever.

pgvector, or a fallback
-----------------------
The intended column type is `vector(384)` with an HNSW index. Where the pgvector
extension is not installed and cannot be installed -- Windows without a
compiler, which is this machine -- the migration creates a plain `real[]` column
instead and `rag/vector_store.py` computes the dot product in SQL.

That is a sequential scan with no ANN index. It is correct but it does not
scale: fine for ~113 chunks, useless at a million. Because embeddings are
L2-normalized, both columns yield identical similarity scores; the fallback
changes how fast a search runs, not what it returns.

Offline mode (`--sql`) cannot probe the server, so it always emits the pgvector
form. That is the right default: offline SQL is reviewed before running against
a real deployment, where pgvector is expected to be present.
"""

from alembic import context, op

revision = "0002_filing_chunks"
down_revision = "0001_initial"
branch_labels = None
depends_on = None

EMBEDDING_DIM = 384


def _pgvector_available() -> bool:
    """Whether `CREATE EXTENSION vector` will succeed on the target server.

    Checked against pg_available_extensions rather than attempted-and-caught: a
    failed CREATE EXTENSION aborts the surrounding transaction, which would take
    the rest of the migration down with it.
    """
    if context.is_offline_mode():
        return True

    bind = op.get_bind()
    available = bind.exec_driver_sql(
        "SELECT COUNT(*) FROM pg_available_extensions WHERE name = 'vector'"
    ).scalar()
    return bool(available)


def upgrade() -> None:
    has_pgvector = _pgvector_available()

    if has_pgvector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        embedding_type = f"vector({EMBEDDING_DIM})"
    else:
        print(
            "  [0002] pgvector not available on this server; "
            "falling back to real[] with exact search and no ANN index."
        )
        embedding_type = "real[]"

    op.execute(f"""
        CREATE TABLE filing_chunks (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            -- Stable identity from the chunker: accession:section:index. Unique
            -- so re-indexing a filing updates rows in place. Appending a second
            -- copy of every chunk would not error, it would just quietly poison
            -- retrieval by having duplicates compete for the top-k.
            chunk_id        TEXT        NOT NULL UNIQUE,

            content         TEXT        NOT NULL,
            token_count     INTEGER     NOT NULL,
            content_type    VARCHAR(16) NOT NULL DEFAULT 'text',

            -- The five metadata fields every chunk is required to carry, plus
            -- the provenance needed to cite a passage back to sec.gov.
            company         TEXT        NOT NULL,
            filing_type     VARCHAR(16) NOT NULL,
            fiscal_period   VARCHAR(16) NOT NULL,
            section         TEXT        NOT NULL,
            chunk_index     INTEGER     NOT NULL,

            ticker          VARCHAR(16) NOT NULL DEFAULT '',
            cik             VARCHAR(10) NOT NULL DEFAULT '',
            accession       VARCHAR(32) NOT NULL DEFAULT '',
            period_end      DATE,
            filing_date     DATE,
            source_url      TEXT        NOT NULL DEFAULT '',

            -- Parsed rows for table chunks, so a tool can do arithmetic on the
            -- numbers instead of re-parsing the rendered text it embedded.
            structured      JSONB,

            -- Which model produced the vector. Embeddings from two models are
            -- not comparable, and a silent model swap makes every stored vector
            -- wrong without changing a single row count.
            embedding_model TEXT        NOT NULL,
            embedding       {embedding_type},

            indexed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT ck_filing_chunks_content_type
                CHECK (content_type IN ('text', 'table'))
        )
    """)

    # Matches the filters search_filings() actually applies.
    op.execute("CREATE INDEX ix_filing_chunks_ticker ON filing_chunks (ticker)")
    op.execute("CREATE INDEX ix_filing_chunks_accession ON filing_chunks (accession)")
    op.execute(
        "CREATE INDEX ix_filing_chunks_ticker_section "
        "ON filing_chunks (ticker, section)"
    )

    if has_pgvector:
        # HNSW over cosine distance. Built on an empty table, which is the cheap
        # order: building after a bulk load costs more than the inserts do.
        op.execute(
            "CREATE INDEX ix_filing_chunks_embedding_hnsw ON filing_chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS filing_chunks")
    # The extension is intentionally left installed: other schemas may use it,
    # and dropping it would cascade away their columns.
